name: Postdeploy

concurrency: ${{ github.ref }}

on:
  workflow_dispatch:
  
    
jobs:
  build:
    # runs-on: windows-latest
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP_NAME: resourceGroupName

    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          
      # az cli installs bicep on demand the first time it's used
      # using the --async argument in the command below simultaniously invokes several commands that use bicep
      # so if bicep isn't already installed, the all initiate the install which throws a file busy error so we
      # execute an arbitrary az bicep command here (and get the latest updates in the process)
      - name: Ensure Bicep
        run: az bicep upgrade

      - name: Postdeploy Bicep
        working-directory: ./src_bicep
        run: az deployment group create 
          --resource-group ${{ env.RESOURCE_GROUP_NAME }}
          --template-file ./postdeploy.bicep 
          --parameters ./parameters/postdeploy.bicepparam